version: '2'
services:
  lb:
    image: dockercloud/haproxy:1.6.7
    ports:
      - 80:80
    environment:
      BALANCE: roundrobin
    links:
      - web
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:3.2
    networks:
      - back-tier
  web:
    build:
      context: .
      args:
        VERSION: "${VERSION}"
    image: "cnsa/some_app:${VERSION}"
    links:
      - redis
    env_file:
      - ./secrets.env
      - ./redis.env
      - ./base.env
    environment:
      VIRTUAL_HOST: some_app.lvh.me
      PORT: 4000
    ports:
      - 8080
    depends_on:
      - redis
    restart: always
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
