version: '2'
services:
  redis:
    image: redis
    networks:
      - back-tier
  web:
    build: .
    image: cnsa/in_fact_test
    links:
      - redis
    env_file:
      - ./freeling.env
      - ./rffi.env
      - ./redis.env
      - ./base.env
    environment:
      VIRTUAL_HOST: apis.rffi.cnsa.ru
      PORT: 4000
    ports:
      - 8080
    depends_on:
      - redis
    restart: always
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
